import { Aleo } from "next/font/google";
import "./globals.css";


const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>{children}</body>
    </html>
  );
}

function App() {
  return (
    <>
    <html lang="en">
      <body className={aleo.className}>
        <Header/>
        {/* <div className="wrapper">
          <main> */}
              {/* <HeroOne />
              <HowItWorks /> */}
              {children}
          {/* </main> */}
        {/* </div> */}
        <Footer />
</body>
</html>
    </>
  )
}

// export default App
