import { Aleo } from "next/font/google";
import "./globals.css";


const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}

export function Header() {
  return (
    <>
    <header>
      <div className="header">
            <h1>🔥 Fireplace Palace</h1>
            </div>
        </header>
    </>
  )
}

export function Footer(){
  return (
  <>
  <footer className="footer">
    <div className="socialLinksList">
      <p>Find us on</p>
      <p>Facebook </p>
      <p>Instagram </p>
      <p>TikTok </p>
      </div>
      <div className="companyInfo">
      <p> (C) Fireplace Palace 2024</p>
      <p>info@firepalace.co.uk</p>
      </div>
  </footer>
  </>
  )
}

// function App() {
//   return (
//     <>
//     <html lang="en">
//       <body className={aleo.className}>
//         <Header/>
//         {/* <div className="wrapper">
//           <main> */}
//               {/* <HeroOne />
//               <HowItWorks /> */}
//               {children}
//           {/* </main> */}
//         {/* </div> */}
//         <Footer />
// </body>
// </html>
//     </>
//   )
// }

// export default App
